### ISSUE TITLE
Error loading current profile data for USER

### ISSUE THREAD

**Issue by EliteMasterEric** [Squagward/JacobStats#1]
Displays "Error loading current profile data for [USER]" (the username entered) for any username that is entered. Cannot see Jacob stats.

**Comment by camnwalter** [comment]
Was the slothpixel or hypixel api down? You can see the errors in /ct console js

**Comment by EliteMasterEric** [comment]
I logged in again and I was able to look at my profile this time.

If I encounter an issue in the future, I will be able to debug it now that I can access the console. I will make a new issue then.

Thank you very much for the help! 😊
